---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint .

platforms:
  - name: instance
    image: ${MOLECULE_DISTRO:-debian:buster}
    privileged: true

provisioner:
  name: ansible

verifier:
  name: ansible
